spring.application.name=meditrack

# Database (smell: password in plain text, and ddl-auto should not be 'update')
spring.datasource.url=jdbc:mysql://localhost:3306/meditrack_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
